import { Footer } from '@/components/Footer/Footer';
import { Navbar } from '@/components/Navbar/Navbar';
import {
  Cormorant,
  Cinzel_Decorative,
  Tangerine,
  Cormorant_Garamond,
  Poppins,
} from 'next/font/google';
import '@/styles/global.scss';
import { ApolloWrapper } from '@/lib/apolloWrapper';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const cormorant = Cormorant({
  subsets: ['latin'],
  variable: '--font-cormorant',
  weight: ['400', '500', '700'],
});

const cormorantGaramond = Cormorant_Garamond({
  subsets: ['latin'],
  variable: '--font-cormorant_garamond',
  weight: ['700'],
});

const cinzelDecorative = Cinzel_Decorative({
  subsets: ['latin'],
  variable: '--font-cinzel_decorative',
  weight: ['400', '700'],
});

const tangerine = Tangerine({
  subsets: ['latin'],
  variable: '--font-tangerine',
  weight: ['400', '700'],
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['500', '700'],
});

const fontsVariablesString = `${cormorant.variable} ${cormorantGaramond.variable} ${cinzelDecorative.variable} ${tangerine.variable} ${poppins.variable}`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloWrapper>
      <html lang="en">
        <body className={fontsVariablesString}>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ApolloWrapper>
  );
}
