name: Jest tests
on: push
jobs:
	test:
		runs-on: ubuntu-latest
		steps:
		- name: Get repository
			uses: actions/checkout@v4
		- name: Yarn install
			run: yarn install
		- name: run test
			run: yarn test
